channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - r-base=4.3.3
  - r-devtools=2.4.5
  - r-vegan=2.6.4
  - bioconductor-phyloseq=1.46.0
  - r-ggplot2=3.5.2
  - r-svglite=2.1.3
  - r-ggpubr=0.6.0
  - r-stringr=1.5.0
  - r-reshape2=1.4.4
  - r-ggh4x=0.2.8
  - r-ggpattern=1.1.4
  - r-ggnewscale=0.5.2
  - r-ape=5.7.1
  - bioconductor-aldex2=1.34.0
  - bioconductor-deseq2=1.42.0
  - bioconductor-enhancedvolcano=1.18.0
  - r-ggtext=0.1.2
  - r-zcompositions=1.4.1
  - r-dplyr=1.1.3
  - r-writexl=1.5.3
  - bioconductor-microbiome=1.24.0
  - r-ggextra=0.10.1
  - r-rstatix=0.7.2
  - r-pracma=2.4.4
  - r-proc=1.18.5
  - r-compositions=2.0.8
