---
title: An R Markdown document converted from "github/Taye_AntihelminthicTreatment_2025/code/analysis/Supplementary
  Figure 1. Microbial diversity. Accounting for STH status.ipynb"
output: html_document
---

### Loading Libraries

```{r}
library(vegan)
library(phyloseq)
library(ranacapa)
library(ape)
library(ggplot2)
library(ggpubr)
library(reshape2)
```

```{r}
# create directories to save files
dir.create(file.path('../../results/figures'), showWarnings = FALSE)
dir.create(file.path('../../results/figures', 'supplementary_figure1'), showWarnings = FALSE)
```

# Alpha Diversity & Rarefraction

### Loading Data

```{r}
# load phyloseq object
ps <- readRDS('../../data/phyloseq/nohost_asv/phyloseq.rds')
ps
```

```{r}
# create a 'time_and_STHStatus' metadata column
# this column has 4 values:
#    baseline_noSTH: a sample is from a baseline cohort, no STH eggs detected at the baseline
#    baseline_STH: a sample is from a baseline cohort, STH eggs detected at the baseline
#    followup_noSTH_noSTH: a sample is from a follow-up cohort, STH-negative at both: the baseline and the follow-up
#    followup_noSTH_STH: a sample is from a follow-up cohort, STH-negative at the baseline, STH-positive at the follow-up
#    followup_STH_noSTH: a sample is from a follow-up cohort, STH-positive at the baseline, STH-negative at the follow-up
#    followup_STH_STH: a sample is from a follow-up cohort, STH-positive at both: the baseline and the follow-up
# p.s. a sample is considered STH-negative at the given collection timepoint, 
# if no STH eggs were detected at the given timpoint
# p.p.s. a sample is considered STH-positive at the given collection timepoint, 
# if at least on STH egg  detected at the given timpoint

# create a new variable (the length = number of of samples) and name everyone as baseline_noSTH
STHStatus <- rep('baseline_noSTH', dim(sample_data(ps))[1])
# mark indexes (TRUE/FALSE) of baseline samples with detected STH at the baseline
STHStatus_baseline_all <- ((sample_data(ps)[['collection_timepoint']] == 'baseline') & 
                       (sample_data(ps)[['sample_eggcountAnySTHs']] > 0))
# rename
STHStatus[STHStatus_baseline_all] <- 'baseline_STH'

# find IDs of participants who were STH-free at the baseline
host_subject_id <- sample_data(ps)[STHStatus == 'baseline_noSTH', ]$host_subject_id
noSTH <- (sample_data(ps)$host_subject_id %in% host_subject_id)&(sample_data(ps)$collection_timepoint == 'follow-up')

# mark indexes as TRUE if 
# 1) a sample is from a follow-up cohort and 
# 2) a sample belongs to the participant who  STH-free at the baseline
STHStatus_followup <- (sample_data(ps)[['collection_timepoint']] == 'follow-up') & noSTH
# name all of them followup_noSTH_noSTH
STHStatus[STHStatus_followup] <- 'followup_noSTH_noSTH'
# mark indexes as TRUE if 
# 1) a sample is from a follow-up cohort and 
# 2) a sample belongs to the participant who  STH-free at the baseline and
# 3) there are STH eggs detected at the follow-up time point
STHStatus_followup <- ((sample_data(ps)[['collection_timepoint']] == 'follow-up') & 
                   (sample_data(ps)[['sample_eggcountAnySTHs']] > 0) & noSTH)
# rename all of them followup_noSTH_STH
STHStatus[STHStatus_followup] <- 'followup_noSTH_STH'

# find IDs of participants who were STH-positive at the baseline
host_subject_id <- sample_data(ps)[STHStatus == 'baseline_STH', ]$host_subject_id
STH <- (sample_data(ps)$host_subject_id %in% host_subject_id)&(sample_data(ps)$collection_timepoint == 'follow-up')
# mark indexes as TRUE if 
# 1) a sample is from a follow-up cohort and 
# 2) a sample belongs to the participant who  STH-positive at the baseline
STHStatus_followup <- (sample_data(ps)[['collection_timepoint']] == 'follow-up') & STH
# rename such samples
STHStatus[STHStatus_followup] <- 'followup_STH_noSTH'
# mark indexes as TRUE if 
# 1) a sample is from a follow-up cohort and 
# 2) a sample belongs to the participant who  STH-positive at the baseline and
# 3) there are STH eggs detected at the follow-up time point
STHStatus_followup <- ((sample_data(ps)[['collection_timepoint']] == 'follow-up') & 
                   (sample_data(ps)[['sample_eggcountAnySTHs']] > 0) & STH)
# rename such samples
STHStatus[STHStatus_followup] <- 'followup_STH_STH'

# create a new column in phyloseq metadata table
sample_data(ps)['time_and_STHStatus'] <- STHStatus
```

### Alpha-diversity
Steps: 
1. Rarefy to the depth 
2. Compute alpha-diversity & assess significance using Wilcoxon signed rank test

```{r}
# set the metadata column we will use for the analysis
comparison_group = 'time_and_STHStatus'
```

#### 1. Rarefy

```{r}
set.seed(295) # setting seed to replicate the randomized rarefraction
# rarefy phyloseq object
ps_rarefied <- rarefy_even_depth(ps, 1e+05)
ps_rarefied
```

```{r}
# look at the rarefraction curve
p <- ggrare(ps_rarefied, step = 1000, color = comparison_group, se = FALSE)
```

### Before Dependent

```{r}
# set plot parameters
comparisons <- unique(sample_data(ps)[[comparison_group]])
symnum.args = list(cutpoints = c(0, 0.0001, 0.001, 0.01, 0.05, 1), symbols = c("****", "***", "**", "*", "ns"))
```

```{r}
# find ids of people who were dewormed
onlydewormed_ids <- sample_data(ps_rarefied)[sample_data(ps_rarefied)[['collection_timepoint']] == 'follow-up',]$host_subject_id
# select only samples from subjects participated in the follow-up study
ps_rarefied_onlywithdewormed <- subset_samples(ps_rarefied, host_subject_id %in% onlydewormed_ids)
# check if the size of the table matches to our expectation
length(onlydewormed_ids)*2 == nsamples(ps_rarefied_onlywithdewormed)
```

```{r}
# compute alpha-diversity metrics
# Tutorial: https://rpubs.com/lconteville/713954
alpha_div <- data.frame(microbiome::alpha(ps_rarefied_onlywithdewormed, 
                                          index=c('observed', 'shannon', 'inverse_simpson')))
colnames(alpha_div) <- c('Observed', 'Shannon', 'Simpson')
alpha_div['ID'] <- row.names(alpha_div)
# add metadata information necessary for the comparison
alpha_div[comparison_group] <- sample_data(ps_rarefied_onlywithdewormed)[alpha_div$ID, comparison_group]
alpha_div[comparison_group] <- factor(alpha_div[[comparison_group]])
levels(alpha_div[comparison_group]) <- c('baseline_noSTH', 
                                   'followup_noSTH_noSTH',
                                   'followup_noSTH_STH',
                                   'baseline_STH', 
                                   'followup_STH_noSTH',
                                   'followup_STH_STH')
alpha_div['host_subject_id'] <- sample_data(ps_rarefied_onlywithdewormed)[alpha_div$ID, 'host_subject_id']
alpha_div['collection_timepoint'] <- sample_data(ps_rarefied_onlywithdewormed)[row.names(alpha_div), 
                                                                            'collection_timepoint']
```

```{r}
# to streamline the statistical comparisons, 
# create a new metadata column that will contain informtions about STH-status 
# at both collection timepoints for each participant
# the format is '[STHStatus at baseline]_[STHStatus at follow-up]'
# noSTH means STH-negative, STH means STH-positive

# For that we will reshape the table, so that one row would contain the information  
# from STH status at baseline and follow-up for one participant
tmp_df <- dcast(data = alpha_div, formula = host_subject_id ~ time_and_STHStatus,
                  fun.aggregate = sum, 
                  value.var = 'Observed')
# create the new column and call all participants STH-free at both time points
tmp_df$STHStatus <- 'noSTH_noSTH'
# rename those participants who acquired STH infection at the follow-up
tmp_df[tmp_df$followup_noSTH_STH > 0, 'STHStatus'] <- 'noSTH_STH'
# rename those participants who had STH-infection at the baseline only
tmp_df[tmp_df$followup_STH_noSTH > 0, 'STHStatus'] <- 'STH_noSTH'
# rename those participants who were STH-positive at the both time points
tmp_df[tmp_df$followup_STH_STH > 0, 'STHStatus'] <- 'STH_STH'
# name table rows witht he participants IDs
row.names(tmp_df) <- tmp_df$host_subject_id

# add the information about STH status at both stages to the alpha diversity table
alpha_div$STHStatus <- tmp_df[alpha_div$host_subject_id, 'STHStatus']
# factorize deworming column to maintain proper order
alpha_div$collection_timepoint <- factor(alpha_div$collection_timepoint, levels=c('follow-up', 'baseline'))
```

```{r}
# compute significance for alpha-diversity metrics by making 4 comparisons:
# 1) compare before/after metrics within the group, who were STH-free at the both timepoints
# 2) compare before/after metrics within the group, who who acquired STH infection at the follow-up
# 3) compare before/after metrics within the group, who had STH-infection at the baseline only
# 4) compare before/after metrics within the group, who were STH-positive at the both time points

test_res <- data.frame()
for (metric in c('Observed', 'Shannon', 'Simpson')) {
    # transform the table for the convenience of the comparison
    div_table <- dcast(data = alpha_div, formula = host_subject_id + collection_timepoint ~ STHStatus,
                  fun.aggregate = sum, 
                  value.var = metric)
    # replace zero values with NaNs to not to skew the statistics with artificial zeros
    div_table['time_and_STHStatus'] <- as.factor(div_table[['time_and_STHStatus']]) 
    div_table[div_table$noSTH_noSTH == 0, 'noSTH_noSTH'] <- NA
    div_table[div_table$noSTH_STH == 0, 'noSTH_STH'] <- NA
    div_table[div_table$STH_noSTH == 0, 'STH_noSTH'] <- NA
    div_table[div_table$STH_STH == 0, 'STH_STH'] <- NA
    
    # 1) compare before/after metrics within the group, who were STH-free at the both timepoints
    stat.test <- compare_means(
      noSTH_noSTH ~ collection_timepoint, data = div_table,
      method = "wilcox.test", paired=TRUE,
      id = 'host_subject_id',
    )
    stat.test['metric'] = metric
    test_res <- rbind(test_res, stat.test)
    
    # 2) compare before/after metrics within the group, who who acquired STH infection at the follow-up
    stat.test <- compare_means(
      noSTH_STH ~ collection_timepoint, data = div_table,
      method = "wilcox.test", paired=TRUE,
      id = 'host_subject_id',
    )
    stat.test['metric'] = metric
    test_res <- rbind(test_res, stat.test)
    
    # 3) compare before/after metrics within the group, who had STH-infection at the baseline only
    stat.test <- compare_means(
      STH_noSTH ~ collection_timepoint, data = div_table,
      method = "wilcox.test", paired=TRUE,
      id = 'host_subject_id',
    )
    stat.test['metric'] = metric
    test_res <- rbind(test_res, stat.test)
    
    # 4) compare before/after metrics within the group, who were STH-positive at the both time points
    stat.test <- compare_means(
      STH_STH ~ collection_timepoint, data = div_table,
      method = "wilcox.test", paired=TRUE,
      id = 'host_subject_id',
    )
    stat.test['metric'] = metric
    test_res <- rbind(test_res, stat.test)
}
# rename some for the consitency between alpha-diversity table metadata and p-values
test_res$group1 <- gsub('follow-up', 'followup_', paste0(test_res$group1, test_res[['.y.']]))
test_res$group2 <- paste0(test_res$group2, '_', lapply(strsplit(test_res[['.y.']], '_'), '[', 1))
# add position for the p-valuss on the plot, custom choice
test_res['y.position'] <- c(1080, 1140, 1080, 1140, 6.2, 6.5, 6.2, 6.5, 220, 240, 220, 240)
test_res
```

```{r}
# recompute alpha-diversity and transform table for plotting
alpha_div <- data.frame(microbiome::alpha(ps_rarefied_onlywithdewormed, 
                                          index=c('observed', 'shannon', 'inverse_simpson')))
colnames(alpha_div) <- c('Observed', 'Shannon', 'Simpson')
alpha_div['ID'] <- row.names(alpha_div)
alpha_div <- melt(alpha_div)
colnames(alpha_div) <- c('ID', 'metric', 'value')
alpha_div[comparison_group] <- sample_data(ps_rarefied_onlywithdewormed)[alpha_div$ID, comparison_group]
alpha_div[comparison_group] <- factor(alpha_div[[comparison_group]])
levels(alpha_div[comparison_group]) <- c('baseline_noSTH', 
                                   'followup_noSTH_noSTH',
                                   'followup_noSTH_STH',
                                   'baseline_STH', 
                                   'followup_STH_noSTH',
                                   'followup_STH_STH')
alpha_div['host_subject_id'] <- sample_data(ps_rarefied_onlywithdewormed)[alpha_div$ID, 'host_subject_id']
```

```{r}
width = 10
height = 7
options(repr.plot.width=width, repr.plot.height=height)
comparisons_stats <- list(c('baseline_noSTH', 
                           'followup_noSTH_noSTH'),
                         c('baseline_noSTH',
                           'followup_noSTH_STH'),
                         c('baseline_STH', 
                           'followup_STH_noSTH'),
                         c('baseline_STH', 
                           'followup_STH_STH'))

p <- ggplot(alpha_div, aes(x=get(comparison_group), y=value)) + 
# lines connecting pairs of samples
      geom_line(aes(x = get(comparison_group), group = host_subject_id), color = "gray", linewidth = 0.5) +
# plot error bar first
      stat_boxplot(aes(color = get(comparison_group)), geom = "errorbar", width = 0.4, lwd=1.3) +
# lay boxplot on top
      geom_boxplot(aes(color = get(comparison_group), 
                       fill=get(comparison_group)), alpha=0.2, lwd=1.3, width=0.5) + 
# overlay alpha-diversity values as dots
      geom_jitter(aes(color = get(comparison_group), fill=get(comparison_group), shape=get(comparison_group)), 
                  size=4, width=0.1, color='black')  + 
# add p-value statistics
      stat_pvalue_manual(data=test_res, label='p.signif', label.size=7) +
# build a separate plot for each alpha-diversity metric
      facet_wrap(~metric, scales = "free_y") + 
# change default colors and shapes
      scale_fill_manual(values = c('#b9bcb5', '#c8b987', '#8e7d41', 
                                   '#878787', '#c8b987', '#8e7d41')) + 
      scale_colour_manual(values = c('#b9bcb5', '#c8b987', '#8e7d41',  
                                     '#878787',  '#c8b987', '#8e7d41')) + 
      scale_shape_manual(values = c(21, 21, 24,  
                                    24, 21, 24)) +
# add titles
      labs(x = "", y = "Diversity value", title = "Microbial Diversity", 
           subtitle = "Baseline & 1-year follow-up depending on STH status") +
# expand y limits to fit the p-value statistics into a plot
      scale_y_continuous(expand = expansion(mult = 0.1)) +
# custom plot design
      theme_minimal() +
      theme(axis.text=element_text(size=15),
            axis.title=element_text(size=25, face="bold"), 
            plot.title=element_text(size=25, face="bold"),
            plot.subtitle=element_text(size=22, face="plain"),
            strip.text = element_text(size = 25, hjust=0, color='#656565'), 
            axis.text.x.bottom = element_text(size=0, angle=90, face='plain', color = "#FFFFFF00", hjust=1),
            axis.text.x = element_blank(),
            axis.title.y = element_text(color='#656565', face='plain'),
            axis.ticks.x=element_line(color = "darkgrey", linewidth = 0.5),
            axis.ticks.length.x.bottom=unit(0.5, "lines"),
            text = element_text(size = 25, face="bold"), 
            axis.line.y = element_line(color = "darkgrey", linewidth = 0.5), 
            axis.line.x.bottom = element_line(color = "darkgrey", linewidth = 0.5), 
            panel.border = element_rect(fill = NA, colour = "grey70", linewidth = rel(1)),
            panel.spacing.x = unit(2, "lines"),
            legend.position="none") 

# ensure the order of the groups at the barplot
p$data[[comparison_group]] <- as.character(p$data[[comparison_group]])
p$data[[comparison_group]] <- factor(p$data[[comparison_group]], 
                                     levels=unlist(c(
                                                   'baseline_noSTH', 
                                                   'followup_noSTH_noSTH',
                                                   'followup_noSTH_STH',
                                                   'baseline_STH', 
                                                   'followup_STH_noSTH',
                                                   'followup_STH_STH')))

# save a plot with a scale of k
k = 0.3
ggsave(file=file.path('../../results/figures', 'supplementary_figure1', 'baseline_followup_STH.alpha_diversity.svg'), plot=p, 
       width=width*k, height=height*k, scaling = k)
# show a plot
print(p)
```

